### ISSUE TITLE
导出身份证信息时丢失精度的问题

### ISSUE THREAD

**Issue by yboker** [zhusaidong/laravel-admin-grid-exporter#1]
导出类似于身份证信息的时候，excel会把它当做数字从而造成丢失精度，通用的解决方案是在身份证后面加一个制表符 ```\t```，转换为字符串。但是这么做是无效的，我看到了下面这行代码：
https://github.com/zhusaidong/laravel-admin-grid-exporter/blob/master/src/Exporter.php#L74
它替我们去除了空格，```\t```也一并去除了，造成导出的数据仍然丢失精度，能否把控制权交给用户，而不是自动去除这些符号？

**Comment by zhusaidong** [comment]
不好意思，今天在外面，明天我看看。
